name: mark-chatbot-app
version: '3'
services:
  db:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mark-chatbot-app